name: Release: attach SBOM

on:
  release:
    types: [published]

jobs:
  attach-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate SBOM (CycloneDX JSON)
        run: npx @cyclonedx/cyclonedx-npm --output-format json --output-file sbom.cdx.json

      - name: Upload SBOM to Release
        uses: softprops/action-gh-release@v2
        with:
          files: sbom.cdx.json
