name: SCA (OSV + Dependency Review)

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  security-events: write     # allow uploading SARIF
  pull-requests: write       # for dependency-review gate

jobs:
  osv-scan:
    # ✅ call the reusable workflow here (top-level 'uses')
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2

  dependency-review:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review (fail on High)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
