name: SAST (Semgrep)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # upload SARIF to Code scanning
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node (cache for quicker runs)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci

      - name: Run Semgrep (OWASP + NodeJS rules)
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/owasp-top-ten
            p/nodejs
          generateSarif: "1"

      - name: Upload SARIF to Code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
